configuración del backend
RichardFelic/conversor-de-moneda pull request #2
Opened 2024-10-29 06:46 UTC by RichardFelic

2024-10-29 07:40 UTC, YolgeSanchez commented on backend/src/controllers/exchangeRateController.ts
nice!

2024-10-29 07:46 UTC, YolgeSanchez commented on backend/src/controllers/userController.ts
> +const handleResponse = (res: Response, statusCode: number, data: any) => {
Recuerda usar este helper para las responses en las funciones "registerUser" y "loginUser"

2024-10-29 07:49 UTC, YolgeSanchez requested changes

2024-10-29 07:49 UTC, YolgeSanchez commented on backend/src/controllers/userController.ts
> +    res.status(204).send();
Aqui en vez de usar res.status(code).send() y enviar un documento vacio puedes usar el metodo del response que seria sendStatus(204) de esta forma:

```js
res.sendStatus(204)
```
Y funcionaria de la misma forma pero mejor a la larga para evitar cualquier posible problema que tal vez ocasione, realmente no se si ocasionaria alguno el devolver un .send() vacio pero por si acaso

2024-10-29 07:51 UTC, YolgeSanchez commented on backend/src/middleware/roleMiddleware.ts
Viste que era super sencillo, quedo nitido

2024-10-29 07:53 UTC, YolgeSanchez commented on backend/src/routes/exchangeRateRoutes.ts
> +router.use(authMiddleware, roleMiddleware([Roles.ADMIN])); // Middleware para proteger las siguientes rutas
NIIICEE!

2024-10-29 07:55 UTC, YolgeSanchez reviewed
Only seeing

2024-10-29 20:34 UTC, RichardFelic commented on backend/src/controllers/userController.ts
> +const handleResponse = (res: Response, statusCode: number, data: any) => {
Justo eso iba a hacer, pero se me olvidó agregarlo. ¡Gracias por avisarme!

2024-10-29 20:39 UTC, RichardFelic commented on backend/src/controllers/userController.ts
> +    res.status(204).send();
Tienes toda la razón evita problemas con los encabezados y tal, y es más limpio.

2024-10-30 03:04 UTC, YolgeSanchez approved these changes

2024-10-30 03:06 UTC, merged